version: "3.2"

services:
  uploader:
    build: .
    command: /home/snapshots
    volumes:
      - .:/home/app
      - ./snapshots:/home/snapshots
      - /home/app/node_modules
      - /home/app/lib/alis-web-index/node_modules
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: "mongo:latest"
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-data:
