version: "3.2"

services:
  uploader:
    build: .
    command: /home/snapshots
    volumes:
      - .:/home/app
      - ./snapshots:/home/snapshots
      - /home/app/node_modules
      - /home/app/lib/alis-web-index/node_modules
    env_file:
      - .env
    restart: on-failure
